import product1 from "../../static/product1.png";
import product2 from "../../static/product2.png";
import product3 from "../../static/product3.png";
import product4 from "../../static/product4.png";
import product5 from "../../static/product5.png";
import product6 from "../../static/product6.png";
import product7 from "../../static/product7.png";
import product8 from "../../static/product8.png";
import product9 from "../../static/product9.png";
import product10 from "../../static/product10.png";

export const products = [
  {
    id: 1,
    category: ["electronic", "gift", "accessory"],
    title: "Z6 Akıllı Saat Kameralı Konuşma Garantili Sim Kartlı Bluetooth",
    label: "Ücretsiz Teslimat",
    price: "399,90 TL",
    img: product1,
  },
  {
    id: 2,
    category: ["gift", "parfume", "personal_care"],
    title: "Calvin Klein Euphoria EDP 100 ml Kadın Parfüm",
    label: null,
    price: "145,61 TL",
    img: product2,
  },
  {
    id: 3,
    category: ["life", "flower", "gift"],
    title: "Gold Çizgili Vazoda 2 Dal Orkide Çiçeği",
    label: "Ücretsiz Teslimat",
    price: "249,90 TL",
    img: product3,
  },
  {
    id: 4,
    category: ["gift", "accessory"],
    title: "925 Ayar Gümüş Çeyreklik Bileklik (Y)",
    label: null,
    price: "329,90 TL",
    img: product4,
  },
  {
    id: 5,
    category: ["spor", "gift", "accessory"],
    title: "Sailor SD-3160 Siyah Dağcı Seyahat Sırt Çantası 55 LT Outdoor-Trekking",
    label: "Ücretsiz Teslimat",
    price: "499,90 TL",
    img: product5,
  },
  {
    id: 6,
    category: ["life", "toy", "gift"],
    title: "Büyük Boy Metal Osmanlı Bizans Satranç Takımı Parlak ve Cevceveli",
    label: "Ücretsiz Teslimat",
    price: "19,90 TL",
    img: product6,
  },
  {
    id: 7,
    category: ["life", "toy", "gift"],
    title: "130 Cm Papyonlu Büyük Ayıcı (%100 Yerli)",
    label: "Ücretsiz Teslimat",
    price: "89,90 TL",
    img: product7,
  },
  {
    id: 8,
    category: ["gift", "accessory"],
    title: "925 Ayar Gümüş Dualı İsimli Nazar İgnesi",
    label: "Ücretsiz Teslimat",
    price: "29,90 TL",
    img: product8,
  },
  {
    id: 9,
    category: ["gift"],
    title: "Özel Tatlar Çikolata Kutusu 300 gr",
    label: "Ücretsiz Teslimat",
    price: "59,90 TL",
    img: product9,
  },
  {
    id: 10,
    category: ["flower", "gift"],
    title: "Kucak Dolusu Aşk 25 Kırmızı Gül Buketi",
    label: null,
    price: "199,90 TL",
    img: product10,
  },
  {
    id: 11,
    category: ["electronic", "gift", "accessory"],
    title: "Z6 Akıllı Saat Kameralı Konuşma Garantili Sim Kartlı Bluetooth",
    label: "Ücretsiz Teslimat",
    price: "399,90 TL",
    img: product1,
  },
  {
    id: 12,
    category: ["gift", "parfume", "personal_care"],
    title: "Calvin Klein Euphoria EDP 100 ml Kadın Parfüm",
    label: null,
    price: "145,61 TL",
    img: product2,
  },
  {
    id: 13,
    category: ["life", "flower", "gift"],
    title: "Gold Çizgili Vazoda 2 Dal Orkide Çiçeği",
    label: "Ücretsiz Teslimat",
    price: "249,90 TL",
    img: product3,
  },
  {
    id: 14,
    category: ["gift", "accessory"],
    title: "925 Ayar Gümüş Çeyreklik Bileklik (Y)",
    label: null,
    price: "329,90 TL",
    img: product4,
  },
  {
    id: 15,
    category: ["spor", "gift", "accessory"],
    title: "Sailor SD-3160 Siyah Dağcı Seyahat Sırt Çantası 55 LT Outdoor-Trekking",
    label: "Ücretsiz Teslimat",
    price: "499,90 TL",
    img: product5,
  },
  {
    id: 16,
    category: ["life", "toy", "gift"],
    title: "Büyük Boy Metal Osmanlı Bizans Satranç Takımı Parlak ve Cevceveli",
    label: "Ücretsiz Teslimat",
    price: "19,90 TL",
    img: product6,
  },
  {
    id: 17,
    category: ["life", "toy", "gift"],
    title: "130 Cm Papyonlu Büyük Ayıcı (%100 Yerli)",
    label: "Ücretsiz Teslimat",
    price: "89,90 TL",
    img: product7,
  },
  {
    id: 18,
    category: ["gift", "accessory"],
    title: "925 Ayar Gümüş Dualı İsimli Nazar İgnesi",
    label: "Ücretsiz Teslimat",
    price: "29,90 TL",
    img: product8,
  },
  {
    id: 19,
    category: ["gift"],
    title: "Özel Tatlar Çikolata Kutusu 300 gr",
    label: "Ücretsiz Teslimat",
    price: "59,90 TL",
    img: product9,
  },
  {
    id: 20,
    category: ["flower", "gift"],
    title: "Kucak Dolusu Aşk 25 Kırmızı Gül Buketi",
    label: null,
    price: "199,90 TL",
    img: product10,
  },
  {
    id: 21,
    category: ["electronic", "gift", "accessory"],
    title: "Z6 Akıllı Saat Kameralı Konuşma Garantili Sim Kartlı Bluetooth",
    label: "Ücretsiz Teslimat",
    price: "399,90 TL",
    img: product1,
  },
  {
    id: 22,
    category: ["gift", "parfume", "personal_care"],
    title: "Calvin Klein Euphoria EDP 100 ml Kadın Parfüm",
    label: null,
    price: "145,61 TL",
    img: product2,
  },
  {
    id: 23,
    category: ["life", "flower", "gift"],
    title: "Gold Çizgili Vazoda 2 Dal Orkide Çiçeği",
    label: "Ücretsiz Teslimat",
    price: "249,90 TL",
    img: product3,
  },
  {
    id: 24,
    category: ["gift", "accessory"],
    title: "925 Ayar Gümüş Çeyreklik Bileklik (Y)",
    label: null,
    price: "329,90 TL",
    img: product4,
  },
  {
    id: 25,
    category: ["spor", "gift", "accessory"],
    title: "Sailor SD-3160 Siyah Dağcı Seyahat Sırt Çantası 55 LT Outdoor-Trekking",
    label: "Ücretsiz Teslimat",
    price: "499,90 TL",
    img: product5,
  },
  {
    id: 26,
    category: ["life", "toy", "gift"],
    title: "Büyük Boy Metal Osmanlı Bizans Satranç Takımı Parlak ve Cevceveli",
    label: "Ücretsiz Teslimat",
    price: "19,90 TL",
    img: product6,
  },
  {
    id: 27,
    category: ["life", "toy", "gift"],
    title: "130 Cm Papyonlu Büyük Ayıcı (%100 Yerli)",
    label: "Ücretsiz Teslimat",
    price: "89,90 TL",
    img: product7,
  },
  {
    id: 28,
    category: ["gift", "accessory"],
    title: "925 Ayar Gümüş Dualı İsimli Nazar İgnesi",
    label: "Ücretsiz Teslimat",
    price: "29,90 TL",
    img: product8,
  },
  {
    id: 29,
    category: ["gift"],
    title: "Özel Tatlar Çikolata Kutusu 300 gr",
    label: "Ücretsiz Teslimat",
    price: "59,90 TL",
    img: product9,
  },
  {
    id: 30,
    category: ["flower", "gift"],
    title: "Kucak Dolusu Aşk 25 Kırmızı Gül Buketi",
    label: null,
    price: "199,90 TL",
    img: product10,
  },
];
